### ISSUE TITLE
createDecipher && Buffer Deprecated

### ISSUE THREAD

**Issue by Dj-jom2x** [someguycrafting/picamo#1]
i manage to fix deprecated buffer but 

line 121 cryptopacker  decryption.cipher = crypto.createDecipher(algorithm, camoOptions.password,);

i change to decryption.cipher = crypto.createDecipher(algorithm, camoOptions.password,);

it throws error: The "iv" argument must be one of type string, Buffer, TypedArray, or DataView. Received type undefined

**Comment by someguycrafting** [comment]
Hi @Dj-jom2x , just pushed a new update that fixes both deprecation warnings and also crypto key sizes.

I've also added a new dependency module [follow-redirects] to allow downloading auto images from loremflickr, since they now may redirect and Node http default implementation has no support for redirection. That being said, you'll need to rerun npm install after fetching the new version.

**Comment by Dj-jom2x** [comment]
does this survive on facebook compression?  someone https://github.com/mathu99/SteganographyForFacebook made research and demo but in pure java xD sorry tbh I don't understand all of this. I'm just aiming to embed some 7 random letters on my auto hashtag finder.. basically users will post our ads .. I can validate the content of the hashtag programmatically but the image. I feel this is the fastest approach. I think I need to at least embed some mini code on it XD and validate on the server side. sorry to bother you.

**Comment by someguycrafting** [comment]
Hi again @Dj-jom2x . There are many steganography techniques that can be applied on an image, but usually they all require that the image is left untouched to some degree. Facebook and other platforms have started applying some image manipulation techniques in order to reduce both bandwidth and disk size, so it's doubtful that this technique (or the one you've linked) will survive Facebook compression as of now.

Still, it's doable, but out of scope for this project.

If you're just aiming at monitoring ad sharing posts on Facebook, wouldn't it just be easier to use Facebook's Graph API to check your user posts for a certain image share? That's just an idea.

**Comment by Dj-jom2x** [comment]
but it's automated. I mean I wanted the script to check if it's my image.. if I put a trademark on it like the hidden text of their username and date .. because anyone can post a random picture and it will still valid.. that's why this stego thingy seems fun to implement hehehe

**Comment by someguycrafting** [comment]
@Dj-jom2x Again, there are many possible ways to implement your use case. If your main goal is not to hide things in images but to have the possibility to monitor who has shared an image, then why not use something as microdot watermarks? These would be tiny dots almost invisible on the image with a unique id that would allow you to map an image (with that unique ID encoded on the microdots) to a specific user. Again, this is just an idea, it's all up to what would work best for your use case.
